### ISSUE TITLE
Specifying a License

### ISSUE THREAD

**Issue by ChristianKrauter** [philip-long/singletact-ros-wrapper#1]
Hi Philip,

thank you for the great code!
I need some adjustments however and would like to create a fork for that.
Could you please specify a license for it?

Thanks in advance,
Chris.

**Comment by philip-long** [comment]
Hi Chris, 

You're very welcome, I'm glad it's useful. I added MIT License file let me know if you've any issues with the code. 

Philip

**Comment by ChristianKrauter** [comment]
Hi Philip,

thank you very much for the quick response!
Unfortunately, I don't need your code anymore as I took a different
approach.
Sry for the late reply and the inconvenience.

Best
Chris

Am Di., 17. Mai 2022 um 13:08 Uhr schrieb philip long <
***@***.***>:
